### ISSUE TITLE
能否兼容MiPushFramework？

### ISSUE THREAD

**Issue by Argon-Pub** [alone-wolf/pushdeer_for_android#1]
机型：OnePlus 8 Pro
系统：Hydrogen OS 11.0.14.14.IN11 (Android 11)
推送：已安装[MiPushFramework](https://github.com/MiPushFramework/MiPushFramework)
问题：无法注册推送服务

希望PushDeer能兼容像MiPushFramework这样的，由第三方提供的MiPush推送框架。

**Comment by Argon-Pub** [comment]
补充图片：
![](https://demo.pubs.net.cn/screenshot/cf200129-261b-4959-b0aa-f6b379d06242.jpg)
![](https://demo.pubs.net.cn/screenshot/5f3598d2-72fa-4e26-acef-b4a34597e206.jpg)

**Comment by alone-wolf** [comment]
MiPushFramework已死

**Comment by alone-wolf** [comment]
到Android9就已经不支持了
